 MAKE_SOB_FRACTION:
  PUSH(FP);
  MOV(FP, SP);
  PUSH(IMM(3));
  CALL(MALLOC);
  DROP(1);
  MOV(IND(R0), T_FRACTION);
  MOV(INDD(R0, 1), FPARG(0)); 
  MOV(INDD(R0, 2), FPARG(1));
  CMP(INDD(R0,1), IMM(0));
  JUMP_GT(CHECK_MEHANE);
  JUMP(CHECK_MEHANE_NEG);
  CHECK_MEHANE:
  CMP(INDD(R0,2), IMM(0));
  JUMP_LT(CHANGE);
  JUMP(END_MAKE_FRACTION);
  CHECK_MEHANE_NEG:
  CMP(INDD(R0,2), IMM(0));
  JUMP_GT(END_MAKE_FRACTION);
  CHANGE:
  MUL(INDD(R0,1), IMM(-1));
  MUL(INDD(R0,2), IMM(-1));
  END_MAKE_FRACTION:
  POP(FP);
  RETURN; 
